name: Update ACTAWP Data - Cadet

on:
  schedule:
   # Executar cada 4 hores: 08:00, 12:00, 16:00, 20:00 UTC (09:00/10:00, 13:00/14:00, 17:00/18:00, 21:00/22:00 hora catalana)
    - cron: '0 8,12,16,20 * * *'
  
  # Permetre executar manualment des de la pestanya Actions
  workflow_dispatch:

jobs:
  update-actawp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Download ACTAWP data
        run: |
          python generate_actawp_json.py
      
      - name: Add timestamp to JSON file
        run: |
          python3 << EOF
          import json
          from datetime import datetime
          
          try:
              with open('actawp_cadet_data.json', 'r', encoding='utf-8') as f:
                  data = json.load(f)
              data['last_update'] = datetime.now().isoformat()
              with open('actawp_cadet_data.json', 'w', encoding='utf-8') as f:
                  json.dump(data, f, ensure_ascii=False, indent=2)
              print("✅ Timestamp afegit a actawp_cadet_data.json")
          except Exception as e:
              print(f"⚠️ Error: {e}")
          EOF
      
      - name: Check if there are changes
        id: check_changes
        run: |
          git diff --exit-code actawp_cadet_data.json || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add actawp_cadet_data.json
          git commit -m "🔄 Actualització automàtica dades ACTAWP Cadet - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
      
      - name: Create summary
        if: always()
        run: |
          echo "### 📊 Actualització ACTAWP Cadet" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Data:** $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
            echo "✅ **Estat:** Dades actualitzades correctament" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ **Estat:** No hi ha canvis respecte l'última actualització" >> $GITHUB_STEP_SUMMARY
          fi